workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      
      - name: Analyze
        script: flutter analyze
      
      - name: Run tests
        script: flutter test
      
      - name: Build Android APK
        script: flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  web-release:
    name: Web Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      
      - name: Build web
        script: flutter build web --release --base-href "/Abilli/"
    
    artifacts:
      - build/web/**
