workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      
      - name: Analyze
        script: flutter analyze
      
      - name: Run tests
        script: flutter test
      
      - name: Build Android with Shorebird
        script: |
          echo $SHOREBIRD_TOKEN | shorebird login --ci
          shorebird release android
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.abilli.app
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: XA7WRS4XL2
        APP_STORE_CONNECT_ISSUER_ID: 87256a58-cb6e-43a1-aef7-dcf36a42acbf
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        SHOREBIRD_TOKEN: $SHOREBIRD_TOKEN
    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.abilli.app \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set up Xcode signing
        script: xcode-project use-profiles

      - name: Get dependencies
        script: flutter pub get

      - name: Analyze
        script: flutter analyze

      - name: Release iOS with Shorebird
        script: |
          echo $SHOREBIRD_TOKEN | shorebird login --ci
          shorebird release ios

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  web-release:
    name: Web Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      
      - name: Build web
        script: flutter build web --release --base-href "/Abilli/"
    
    artifacts:
      - build/web/**
